### ISSUE TITLE
cannot load the ur10 correctly

### ISSUE THREAD

**Issue by ChenyangRan** [jr-robotics/robo-gym-robot-servers#3]
Hi, I have installed this ros_pkg as the tutorial. However, the following command cannot work well.
```
roslaunch ur_robot_server ur10_sim_robot_server.launch gui:=true
```
The error is 
```
Invalid <arg> tag: Unknown substitution command [dirname]. Valid commands are ['find', 'env', 'optenv', 'anon', 'arg']. 

Arg xml is <arg default="$(dirname)/inc/load_ur10.launch.xml" doc="Launch file which populates the 'robot_description' parameter." name="robot_description_file"/>

```
Could you help me?
I can roslaunch the ur10 as the guide in universal_robot.

**Comment by matteolucchi** [comment]
Hi @ChenyangRan and thank you for using robo-gym! 

As it is mentioned at the top of the README of this repository:

> WARNING: The compatibility of the Universal Robots environments with ROS Kinetic has been maintained until version v0.1.8 included. After this version we integrated a refactored version of the universal_robot repository which is not compatible with ROS Kinetic. We will try to maintain backwards compatibility but if you encounter issues please use v0.1.8 or switch to ROS Melodic.

The issue here is that we switched to the [melodic-devel-staging branch](https://github.com/ros-industrial/universal_robot/tree/melodic-devel-staging) of [ros-industrial/universal_robot](https://github.com/ros-industrial/universal_robot) and in the new launch file structure it is used the _$dirname_ argument, which is only supported in launch files from ROS Melodic. 

As mentioned in the README you can try to revert back to v0.1.8 of this repository:
```
cd ~/robogym_ws/src/robo-gym-robot-servers
git checkout v0.1.8
cd ~/robogym_ws
catkin build
```

Nevertheless I would suggest you to switch to Ubuntu 18.04 and ROS Melodic + Gazebo 9, especially for the UR Robots we found several improvements in the simulation that were fixed with Gazebo 9. 

Cheers, 
Matteo
